nodeLinker: node-modules

initFields:
  author: Strukt Team (github.com/strukt-js)
  repository: "git@github.com:strukt-js/strukt-typescript-preset.git"

initScope: strukt

yarnPath: .yarn/releases/yarn-3.2.0.cjs
